name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 MSG_01 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 MSG_02 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 MSG_03 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 MSG_04 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ MSG_05 The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 MSG_06 This job's status is ${{ job.status }}."
